[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hearthstone-misc-asset-extractor"
version = "0.1.1"
requires-python = ">=3.12"

dependencies = [
    "nuitka>=4.1.3",
    "unitypy>=1.25.2",
]


[project.scripts]
misc-asset = "cli:main"
build = "build_script:build"
